export const SET_SORT_BY = 'SET_SORT_BY'
export const SET_CATEGORY = 'SET_CATEGORY'
export const SETPIZZAS = 'SETPIZZAS'
export const SET_LOADED = 'SET_LOADED'
export const SET_TOTAL_PRICE = 'SET_TOTAL_PRICE'
export const SET_TOTAL_COUNT = 'SET_TOTAL_COUNT'
